version: '3'

volumes:
  rabbitmq-data:

services:
  controller:
    image: loan-controller
    build:
      context: .
      dockerfile: ./Dockerfile.controller
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ETCD_HOST=etcd
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - etcd
      - rabbitmq

  worker:
    image: loan-worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ETCD_HOST=etcd
    restart: unless-stopped
    depends_on:
      - etcd
      - rabbitmq

  etcd:
    image: bitnami/etcd:3.4.9
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      #- "5671:5671"
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
